# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bb3b555654bbde13121c625069e6b59a93004359f41ae89e5f4ddfadc562538073f87d6e1ca2f7e2c9946274a8b7a23d6b06b2b156566d86ecddd91684e1766

test:
  secret_key_base: 3c91f91909bd548af1a007a3ee427a06565896375a3c317e25ccc1652be60fe3d9a5d8a88ba8ed4233eb7b0bbabb9dfa5d40f506e4918dde229fec3acc1b0126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
